Hypermarket data pipeline initial draft
fcabrera23/arc_jumpstart_docs pull request #25
Opened 2024-11-11 15:07 UTC by chintalavr

This PR includes following documentation

1. Microsoft Fabric workspace setup instructions
2. Commercial data pipeline
3. Operational data pipeline

2024-11-11 15:33 UTC, sebassem requested changes
Minor modifications

2024-11-11 15:33 UTC, sebassem commented on docs/azure_jumpstart_ag/contoso_hypermarket/deployment/_index.md
> +Due to some limitations of automating Microsoft Fabric items in the Fabric workspace using managed identity, users deploying Contoso Hypermarket have to run a Microsoft Fabric workspace setup script
```suggestion
Due to some limitations of automating Microsoft Fabric items in the Fabric workspace using a managed identity, users deploying Contoso Hypermarket have to run a setup script manually using the end user credentials that are used to access Microsoft Fabric workspace.
```

2024-11-11 15:33 UTC, sebassem commented on docs/azure_jumpstart_ag/contoso_hypermarket/deployment/_index.md
> +In order to create Microsoft Fabric workspace, tenant in which workspace is created must have one of the following settings enabled. Users can verify these settings in [Microsoft Fabric Admin Portal]
```suggestion
In order to create the Microsoft Fabric workspace, the tenant in which the workspace is created must have one of the following settings enabled. Users can verify these settings in [Microsoft Fabric Admin Portal](https://app.powerbi.com/admin-portal/tenantSettings?experience=power-bi). If you do not have permissions to access Microsoft Fabric Admin Portal, please contact your Entra ID tenant to confirm these settings.
```

2024-11-11 15:33 UTC, sebassem commented on docs/azure_jumpstart_ag/contoso_hypermarket/deployment/_index.md
> +- Users are prompted to complete authentication using code to log into the Entra ID tenant to create fabric workspace. Copy 1) device authentication URL and 2) Code from the command-line as shown bel
```suggestion
- Users are prompted to complete authentication using a device code to log into the Entra ID tenant to create fabric workspace. Copy 1) device authentication URL and 2) Code from the command-line as shown below.
```

2024-11-11 15:33 UTC, sebassem commented on docs/azure_jumpstart_ag/contoso_hypermarket/deployment/_index.md
> +  ![Screenshot showing subscription selection](./img/fabric-select-subsription.png)
I think the blurring is messed up, the image looks a little bit confusing

2024-11-12 01:38 UTC, chintalavr commented
I have updated as per the review comments

2024-11-12 15:22 UTC, merged