Checking in updates to camera, zones and regions documentation
fcabrera23/arc_jumpstart_docs pull request #36
Opened 2024-11-12 20:56 UTC by nabeelmsft

Checking in updates to camera, zones and regions documentation

2024-11-12 22:45 UTC, nabeelmsft commented on docs/azure_jumpstart_ag/contoso_hypermarket/shopper_insights/_index.md
This has been resolved by commit:  24e60f49e8a5a65d09549568e4db2cb3f741c87f

2024-11-13 00:01 UTC, nabeelmsft commented
> Great work, looks great :)
> 
> * Please use bullets for each step
> * The architecture diagram should be at the start of the page - See other scenarios
> * Please see the Valve errors (spelling, grammar,...etc). Look at the PR checks for that
> * For images requiring multiple steps try to use numbering in circles. See https://raw.githubusercontent.com/Azure/arc_jumpstart_docs/main/docs/azure_jumpstart_arcbox/DataOps/sql_stress_start.png

Thanks @sebassem for the review. Great points. I have addressed all the issues per your suggestions, and they have been checked in. Regarding the architecture diagram, after talking to @dkirby-ms, it was concluded that we will keep the location where it is right now.

2024-11-13 16:02 UTC, sebassem requested changes
Minor comments and please refactor the last section to be like [this one ](https://arcjumpstart-ignite.azurewebsites.net/azure_jumpstart_ag/contoso_hypermarket/deployment#next-steps)

2024-11-13 16:02 UTC, sebassem commented on docs/azure_jumpstart_ag/contoso_hypermarket/shopper_insights/_index.md
> +    ![A screenshot draw floor zones page](./drawfloorzones.png)
Please add a ref arrow to show where the user needs to click

2024-11-13 16:29 UTC, nabeelmsft commented on docs/azure_jumpstart_ag/contoso_hypermarket/shopper_insights/_index.md
> +    ![A screenshot draw floor zones page](./drawfloorzones.png)
This the image is not meant to show where to click. The purpose of the image is to show how the page will look like when they come to this page after completing the previous step. The subsequent actions are already defined in the next step.

2024-11-13 16:30 UTC, nabeelmsft commented on docs/azure_jumpstart_ag/contoso_hypermarket/shopper_insights/_index.md
> +    ![A screenshot showing Upload floor plan step with "Next" button highlighted](./uploadfloorplan.png)
This has been fixed as part of commit: 4735d4cadd7527856e48bc9a04e108fdc07b8d65

2024-11-13 16:33 UTC, sebassem commented on docs/azure_jumpstart_ag/contoso_hypermarket/shopper_insights/_index.md
> +    ![A screenshot draw floor zones page](./drawfloorzones.png)
got you :)

2024-11-13 18:11 UTC, merged