First Draft of the Cerebral Documentation
fcabrera23/arc_jumpstart_docs pull request #42
Opened 2024-11-13 00:01 UTC by armandoblanco

1. Links to products and other sections need to be added.
2. At the end of the document, there is a section for pending topics that will be incorporated.

2024-11-13 10:12 UTC, sebassem requested changes
Great work, looks great. Some minor comments:

- The diagrams are not High Res, make sure to export from ppt instead of snipping
- I feel the scenario needs more step-by-step on how to use Cerebral to do some tasks rather than an extensive explanation of what Cerebral is (we need that as well but more of how can the user actually use it with screenshots)
- Move everything related to the architecture, design and capabilities to the top before showing a practical step-by-step guide on how Contoso can use it

2024-11-13 10:12 UTC, sebassem commented on docs/azure_jumpstart_ag/contoso_hypermarket/cerebral/_index.md
> +### Business Challenges
Let's re-write this section to be Contoso Hypermarket focused instead of generic

2024-11-13 10:12 UTC, sebassem commented on docs/azure_jumpstart_ag/contoso_hypermarket/cerebral/_index.md
> +Throughout the Contoso Hypermarket interface, whether you're a store manager reviewing sales data, a maintenance technician checking equipment status, or a shopper seeking assistance, you'll find the
lets add a screenshot and a URL to where they can see this icon and let's remove it from the text

2024-11-13 10:12 UTC, sebassem commented on docs/azure_jumpstart_ag/contoso_hypermarket/cerebral/_index.md
> +| Type of Query | Example Question | Sample Response |
Let's add a note saying that results might differ from the screenshots

2024-11-13 10:12 UTC, sebassem commented on docs/azure_jumpstart_ag/contoso_hypermarket/cerebral/_index.md
> +## Architecture
Let's move this section up after the overview

2024-11-13 10:12 UTC, sebassem commented on docs/azure_jumpstart_ag/contoso_hypermarket/cerebral/_index.md
> +The following table details the equipment types and metrics being simulated through MQTT for Contoso Hypermarket operations:
```suggestion
The following table details the equipment types and metrics being simulated through MQTT for Contoso Hypermarket's operations:
```

2024-11-13 10:12 UTC, sebassem commented on docs/azure_jumpstart_ag/contoso_hypermarket/cerebral/_index.md
> +At its core, Cerebral employs a query processing orchestrator that intelligently routes requests to appropriate data sources based on the nature of the query. For commercial data such as sales, inven
```suggestion
At its core, Cerebral employs a query processing orchestrator that intelligently routes requests to appropriate data sources based on the nature of the query. For commercial data such as sales, inventory, and customer information, the system interfaces with SQL Server. Real-time device metrics and operational data are managed through InfluxDB, a specialized time-series database that captures everything from equipment performance to environmental readings. Technical documentation and operational procedures are accessed through a [Chroma vector database](https://www.trychroma.com/), enabling powerful RAG (Retrieval Augmented Generation) capabilities.
```

2024-11-13 12:47 UTC, armandoblanco commented on docs/azure_jumpstart_ag/contoso_hypermarket/cerebral/_index.md
> +Cerebral innovative hybrid architecture optimally balances edge computing with cloud capabilities. Whether processing queries via [Azure OpenAI](https://learn.microsoft.com/en-us/azure/ai-services/op
That URL is very generic, and I use it later.

2024-11-13 16:04 UTC, sebassem commented on docs/azure_jumpstart_ag/contoso_hypermarket/cerebral/_index.md
> +Cerebral innovative hybrid architecture optimally balances edge computing with cloud capabilities. Whether processing queries via [Azure OpenAI](https://learn.microsoft.com/en-us/azure/ai-services/op
I see, we should always point to docs or official pages like azure.microsoft.com instead of blog posts so if you can find a better URL let's add it 👍

2024-11-13 16:10 UTC, sebassem requested changes
Some additional comments on top of the first review

2024-11-13 16:10 UTC, sebassem commented on docs/azure_jumpstart_ag/contoso_hypermarket/cerebral/_index.md
> +   - Locate the Cerebral icon in the top-right corner of any page
Lets add steps and screenshots to opening this page from the bookmarks in the environment (not all users to follow the order we have in the docs so its important if a user lands on Cerebral docs to know which website to open)

2024-11-13 16:10 UTC, sebassem commented on docs/azure_jumpstart_ag/contoso_hypermarket/cerebral/_index.md
> +<img src="./img/cerebral-location.png" alt="Cerebral location" width="500"/>
Please change this to markdown format instead of HTML, Also take a full screenshot from the browser no cropped (a little bit zoomed in :) )

2024-11-13 16:35 UTC, armandoblanco commented on docs/azure_jumpstart_ag/contoso_hypermarket/cerebral/_index.md
> +   - Locate the Cerebral icon in the top-right corner of any page
it seems to me that this should be covered in the main web app, and here I can put a reference, is that ok?

2024-11-13 16:36 UTC, armandoblanco commented on docs/azure_jumpstart_ag/contoso_hypermarket/cerebral/_index.md
> +At its core, Cerebral employs a query processing orchestrator that intelligently routes requests to appropriate data sources based on the nature of the query. For commercial data such as sales, inven
Done

2024-11-13 16:36 UTC, armandoblanco commented on docs/azure_jumpstart_ag/contoso_hypermarket/cerebral/_index.md
> +The following table details the equipment types and metrics being simulated through MQTT for Contoso Hypermarket operations:
Done

2024-11-13 16:37 UTC, armandoblanco commented on docs/azure_jumpstart_ag/contoso_hypermarket/cerebral/_index.md
> +## Architecture
Done

2024-11-13 16:37 UTC, armandoblanco commented on docs/azure_jumpstart_ag/contoso_hypermarket/cerebral/_index.md
> +| Type of Query | Example Question | Sample Response |
Done

2024-11-13 16:37 UTC, armandoblanco commented on docs/azure_jumpstart_ag/contoso_hypermarket/cerebral/_index.md
> +Throughout the Contoso Hypermarket interface, whether you're a store manager reviewing sales data, a maintenance technician checking equipment status, or a shopper seeking assistance, you'll find the
Done, I have added step by step instructions and more images

2024-11-13 16:37 UTC, armandoblanco commented on docs/azure_jumpstart_ag/contoso_hypermarket/cerebral/_index.md
> +> **Learn More**: For detailed information about Cerebral's Generative AI capabilities, explore the [Azure OpenAI Service documentation](https://learn.microsoft.com/en-us/azure/ai-services/openai/ove
Done

2024-11-13 16:39 UTC, armandoblanco commented on docs/azure_jumpstart_ag/contoso_hypermarket/cerebral/_index.md
> +<img src="./img/logo.png" alt="Equipment monitoring" width="100"/>
To create the Cerebral branding, I would really like to keep it

2024-11-13 16:57 UTC, armandoblanco commented on docs/azure_jumpstart_ag/contoso_hypermarket/cerebral/_index.md
> +<img src="./img/cerebral-location.png" alt="Cerebral location" width="500"/>
Done. I have applied the change to this image

2024-11-13 17:05 UTC, armandoblanco commented on docs/azure_jumpstart_ag/contoso_hypermarket/cerebral/_index.md
> +   - Locate the Cerebral icon in the top-right corner of any page
Done. I have added a reference to Shopper Insight where the navigation of the web apps is explained.

2024-11-14 03:44 UTC, likamrat commented on docs/azure_jumpstart_ag/contoso_hypermarket/cerebral/_index.md
> +<img src="./img/logo.png" alt="Equipment monitoring" width="100"/>
It is also not using the diagrams from the Agora deck

2024-11-14 13:25 UTC, sebassem commented on docs/azure_jumpstart_ag/contoso_hypermarket/cerebral/_index.md
> +<img src="./img/logo.png" alt="Equipment monitoring" width="100"/>
I talked with Lior, lets keep the logo

2024-11-14 18:57 UTC, armandoblanco commented on docs/azure_jumpstart_ag/contoso_hypermarket/cerebral/_index.md
> +Cerebral innovative hybrid architecture optimally balances edge computing with cloud capabilities. Whether processing queries via [Azure OpenAI](https://learn.microsoft.com/en-us/azure/ai-services/op
It's not the content, nor the message I want to share, but I've already made the change

2024-11-14 18:59 UTC, armandoblanco commented on docs/azure_jumpstart_ag/contoso_hypermarket/cerebral/_index.md
> +### Business Challenges
I would like to leave generic, because as part of Cerebral's branding we want to say that it is generic and can be adapted to multiple industries.

2024-11-14 19:00 UTC, armandoblanco commented on docs/azure_jumpstart_ag/contoso_hypermarket/cerebral/_index.md
> +![Operational Challenges](./img/operational-challenges.png)
Done

2024-11-14 23:40 UTC, merged