Infra Observability
fcabrera23/arc_jumpstart_docs pull request #57
Opened 2024-11-13 22:19 UTC by mrhoads

This PR adds screenshots and update info on infra observability and attempts to incorporate feedback from PR #40 (since closed).

2024-11-13 22:27 UTC, sebassem requested changes
LGTM, just minor updates and missing diagram

2024-11-13 22:27 UTC, sebassem commented on docs/azure_jumpstart_ag/contoso_hypermarket/observability/infrastructure/_index.md
> +
I think we are missing the diagram here

2024-11-13 22:27 UTC, sebassem commented on docs/azure_jumpstart_ag/contoso_hypermarket/observability/infrastructure/_index.md
> +- **Kubernetes / Views / Global**: The Kubernetes Global Dashboard in Grafana offers a concise overview of your Kubernetes cluster, allowing you to quickly assess its overall health and performance.
```suggestion
- **Kubernetes / Views / Global**: The Kubernetes Global Dashboard in Grafana offers a concise overview of Contoso's Kubernetes cluster, allowing them to quickly assess its overall health and performance. The dashboard includes panels that highlight key metrics, such as total cluster CPU, RAM, and network utilization, as well as resource usage across namespaces and nodes. Additionally, it tracks the number of resource types used in the cluster and helps detect misconfigured application resources by comparing real usage with requested and limited resources.
```

2024-11-13 22:27 UTC, sebassem commented on docs/azure_jumpstart_ag/contoso_hypermarket/observability/infrastructure/_index.md
> +- **Node Exporter Full**: The Kubernetes Nodes Dashboard in Grafana provides a detailed view of node-level metrics and resources in your Kubernetes cluster. It enables you to monitor CPU and RAM usag
```suggestion
- **Node Exporter Full**: The Kubernetes Nodes Dashboard in Grafana provides a detailed view of node-level metrics and resources in Contoso's Kubernetes cluster. It enables you to monitor CPU and RAM usage, track pods running on each node, and identify any resource anomalies or performance issues. The dashboard also offers system-level metrics such as system load, context switches, and file descriptors, allowing for troubleshooting and optimization. Additionally, it provides insights into storage capacity, volumes, and I/O operations on the nodes, aiding in the effective management of storage resources.
```

2024-11-13 22:27 UTC, sebassem commented on docs/azure_jumpstart_ag/contoso_hypermarket/observability/infrastructure/_index.md
> +- Connect to the Client VM _Ag-VM-Client_ using the instruction in the [deployment guide](../deployment/)
```suggestion
- Connect to the Client VM _Ag-VM-Client_ using the instructions in the [deployment guide](../deployment/)
```

2024-11-14 01:22 UTC, mrhoads commented
closing after fetching latest updates from canary

2024-11-14 01:22 UTC, closed without merging